services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - netchecador

  app:
    build:
      args:
        user: dgtit
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - netchecador
    ports:
      - 5173:5173

  worker-schedule:
    build:
      args:
        user: dgtit
        uid: 1000
      context: .
      dockerfile: ./Dockerfile.worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: php /var/www/html/artisan schedule:work
    networks:
      - netchecador

  worker-queue:
    build:
      args:
        user: dgtit
        uid: 1000
      context: .
      dockerfile: ./Dockerfile.worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - netchecador

networks:
  netchecador: